In [62]:
import pandas as pd

In [63]:
df= pd.read_csv("/content/Titanic-Dataset.csv")

In [64]:
# Q1: How many passengers were in First Class?
ans1 = df[df['Pclass'] == 1].shape[0]
ans1

216

In [65]:
# Q2 How many passenger were male?
ans2 = df[df['Sex'] == 'male'].shape[0]
ans2

577

In [66]:
# Q3 how many passenger were belong to the cabinet c85
ans3 = df[df['Cabin'] == 'C85'].shape[0]
ans3

1

In [67]:
# Q4: Get the list of all female passengers who survived.
ans4 = df[(df['Sex'] == 'female') & (df['Survived']== 1) ]['Name']
ans4

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
8      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                    Nasser, Mrs. Nicholas (Adele Achem)
                             ...
874                Abelson, Mrs. Samuel (Hannah Wizosky)
875                     Najib, Miss. Adele Kiamie "Jane"
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
880         Shelley, Mrs. William (Imanita Parrish Hall)
887                         Graham, Miss. Margaret Edith
Name: Name, Length: 233, dtype: object

In [68]:
# Q5: What is the average age of passengers who did not survive?
ans5 = df[(df['Survived'] == 0)]['Age'].mean()
ans5

np.float64(30.62617924528302)

In [69]:
# Q6 List a passenger name who paid a fare greater than $200
ans6 = df[(df['Fare'] > 200)]['Name']
ans6

27                        Fortune, Mr. Charles Alexander
88                            Fortune, Miss. Mabel Helen
118                             Baxter, Mr. Quigg Edmond
258                                     Ward, Miss. Anna
299      Baxter, Mrs. James (Helene DeLaudeniere Chaput)
311                           Ryerson, Miss. Emily Borie
341                       Fortune, Miss. Alice Elizabeth
377                            Widener, Mr. Harry Elkins
380                                Bidois, Miss. Rosalie
438                                    Fortune, Mr. Mark
527                                   Farthing, Mr. John
557                                  Robbins, Mr. Victor
679                   Cardeza, Mr. Thomas Drake Martinez
689                    Madill, Miss. Georgette Alexandra
700    Astor, Mrs. John Jacob (Madeleine Talmadge Force)
716                        Endres, Miss. Caroline Louise
730                        Allen, Miss. Elisabeth Walton
737                               Lesurer, Mr. Gustave J
742                Ryerson, Miss. Susan Parker "Suzette"
779    Robert, Mrs. Edward Scott (Elisabeth Walton Mc...
Name: Name, dtype: object

In [70]:
# Q7 How many passenger were embarked from S
ans7 = df[df['Embarked'] == 'S'].shape[0]
ans7

644

In [71]:
# Q8 how many passenger had age greater than 60 and survived
ans8 = df[(df['Age']  > 60 )  & (df['Survived'] == 1)].shape[0]
ans8

5

In [72]:
# Q9 list the detail of passenger who have no siblings and no parents on board
ans9 = df[(df['SibSp'] == 0) & ( df['Parch'] == 0)]
ans9

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [73]:
# Q10 who was the oldest passenger on boat
ans10 = df.loc[df['Age'].idxmax()]
ans10

PassengerId                                     631
Survived                                          1
Pclass                                            1
Name           Barkworth, Mr. Algernon Henry Wilson
Sex                                            male
Age                                            80.0
SibSp                                             0
Parch                                             0
Ticket                                        27042
Fare                                           30.0
Cabin                                           A23
Embarked                                          S
Name: 630, dtype: object